### ISSUE TITLE
Deploying

### ISSUE THREAD

**Issue by dbilovd** [Sylvestre5/vue-weather#1]
@Sylvestre5 kindly take a look at [this document](https://cli.vuejs.org/guide/deployment.html#general-guidelines) it contains information on how to deploy it. Try to deploy it on any one of the following services:

[Heroku](https://www.heroku.com) or [Netflify](https://www.netlify.com)

**Comment by Sylvestre5** [comment]
> @Sylvestre5 kindly take a look at [this document](https://cli.vuejs.org/guide/deployment.html#general-guidelines) it contains information on how to deploy it. Try to deploy it on any one of the following services:
> 
> [Heroku](https://www.heroku.com) or [Netflify](https://www.netlify.com)

Thanks... Just did. It's amazing using Heroku.

**Comment by dbilovd** [comment]
Great. 

You can update the README.md file with the link, so anyone that visits the Github page can immediately use it and see how it works.

**Comment by Sylvestre5** [comment]
Okay.. Well Noted with thanks.
